name: Test

on:
  push:
    branches:
      - main
      - bestie
    tags: ["*"]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ReusableTest.yml
    with:
      os: ${{ matrix.os }}
      version: ${{ matrix.version }}
      arch: ${{ matrix.arch }}
      run_codecov: ${{ matrix.version == '1' && matrix.os == 'ubuntu-latest' }}
      build_is_production_build: ${{ matrix.build_is_production_build }}
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.10'
          - '1'
        os:
          - ubuntu-latest
        build_is_production_build:
          - true
        arch:
          - x64
        include:
          - os: windows-latest
            arch: x64
            version: 1
            build_is_production_build: true
          - os: macOS-latest
            arch: aarch64
            version: 1
            build_is_production_build: true
